// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCth985IgK_bI6b7KNxVpEzvNnoWne3zGk',
    appId: '1:306151241493:web:130e6cb25666b39f16db1c',
    messagingSenderId: '306151241493',
    projectId: 'appdatxe-3be95',
    authDomain: 'appdatxe-3be95.firebaseapp.com',
    storageBucket: 'appdatxe-3be95.firebasestorage.app',
    measurementId: 'G-SC5YM87RTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8y2QZ9zDKDKxS0ob7ktWRBbX8wPQBQzs',
    appId: '1:306151241493:android:9bca222eb5e1420516db1c',
    messagingSenderId: '306151241493',
    projectId: 'appdatxe-3be95',
    storageBucket: 'appdatxe-3be95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvesAS3dS9528qZDOqSeIkAfek1C2h7bw',
    appId: '1:306151241493:ios:a48a32aa163f4ac116db1c',
    messagingSenderId: '306151241493',
    projectId: 'appdatxe-3be95',
    storageBucket: 'appdatxe-3be95.firebasestorage.app',
    iosBundleId: 'net.donvaden.taxi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvesAS3dS9528qZDOqSeIkAfek1C2h7bw',
    appId: '1:306151241493:ios:d87a6349353768dc16db1c',
    messagingSenderId: '306151241493',
    projectId: 'appdatxe-3be95',
    storageBucket: 'appdatxe-3be95.firebasestorage.app',
    iosBundleId: 'com.example.waterReminder',
  );
}
